name: pull_point
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Value equality
  equatable: ^2.0.3
  
  # Remote API
  http: ^0.13.4

  # Local cache
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11

  # Bloc / Cubit for state management
  flutter_bloc: ^8.0.1

  # Map
  flutter_map: ^2.0.0
  latlong2: ^0.8.1
  location: ^4.4.0

  # Date format
  intl: ^0.17.0

  # UI
  sliding_up_panel: ^2.0.0+1
  carousel_slider: ^4.1.1

  # toasts
  bot_toast: ^4.0.3

  # validation
  email_validator: ^2.1.17
  mask_text_input_formatter: ^2.4.0

  # QR
  qr_flutter: ^4.0.0
  mobile_scanner: ^2.1.0

  # Push Notification
  firebase_core: ^2.5.0
  flutter_local_notifications: ^13.0.0
  firebase_messaging: ^14.2.2
  cloud_firestore: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # code gen
  hive_generator: ^1.1.3
  build_runner: ^2.2.0

  # App Icon
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  ios: true
  android: "launcher_icon"
  image_path: "assets/raster/launcher_icon/icon.png"
  adaptive_icon_background: "assets/raster/launcher_icon/background.png"
  adaptive_icon_foreground: "assets/raster/launcher_icon/foreground.png"

flutter:
  uses-material-design: true

  assets:
    - assets/raster/images/
    - assets/raster/launcher_icon/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
